-- Create a table for game rooms
create table game_rooms (
  id bigint generated by default as identity primary key,
  room_code text not null unique,
  data jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Realtime for this table
alter publication supabase_realtime add table game_rooms;

-- Create a policy to allow anyone to read/write (since we are doing a simple demo without auth)
-- Note: In a production app, you should enable RLS and add proper policies.
alter table game_rooms enable row level security;

create policy "Enable read access for all users"
on game_rooms for select
using (true);

create policy "Enable insert access for all users"
on game_rooms for insert
with check (true);

create policy "Enable update access for all users"
on game_rooms for update
using (true);
