-- ============================================================
-- v2026-02-04: Room membership + storyteller auth hardening
-- ============================================================

-- Ensure crypto extension for UUIDs
create extension if not exists pgcrypto;

-- Add storyteller_id for ownership
alter table if exists game_rooms
  add column if not exists storyteller_id uuid;

create index if not exists idx_game_rooms_storyteller_id on game_rooms(storyteller_id);

-- Room members table
create table if not exists room_members (
  id bigint generated by default as identity primary key,
  room_id bigint not null references game_rooms(id) on delete cascade,
  user_id uuid not null,
  display_name text,
  role text not null default 'player',
  seat_id int,
  seen_role_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(room_id, user_id)
);

-- Game secrets (storyteller-only)
create table if not exists game_secrets (
  room_code text primary key references game_rooms(room_code) on delete cascade,
  data jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Game history (archived finished games)
create table if not exists game_history (
  id bigint generated by default as identity primary key,
  room_code text not null references game_rooms(room_code) on delete cascade,
  winner text,
  reason text,
  script_name text,
  players jsonb,
  messages jsonb,
  state jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable realtime where needed (ignore duplicates)
do $$
begin
  alter publication supabase_realtime add table room_members;
exception when duplicate_object then
  null;
end $$;

do $$
begin
  alter publication supabase_realtime add table game_history;
exception when duplicate_object then
  null;
end $$;

-- ============================================================
-- Row Level Security
-- ============================================================

alter table game_rooms enable row level security;
alter table room_members enable row level security;
alter table game_secrets enable row level security;
alter table game_messages enable row level security;
alter table seat_secrets enable row level security;
alter table interaction_logs enable row level security;
alter table daily_nominations enable row level security;
alter table game_history enable row level security;

-- game_rooms policies
DROP POLICY IF EXISTS "game_rooms_select" ON game_rooms;
DROP POLICY IF EXISTS "game_rooms_insert" ON game_rooms;
DROP POLICY IF EXISTS "game_rooms_update" ON game_rooms;

CREATE POLICY "game_rooms_select"
  ON game_rooms FOR SELECT
  USING (auth.role() = 'service_role' OR auth.uid() IS NOT NULL);

CREATE POLICY "game_rooms_insert"
  ON game_rooms FOR INSERT
  WITH CHECK (auth.role() = 'service_role' OR auth.uid() = storyteller_id);

CREATE POLICY "game_rooms_update"
  ON game_rooms FOR UPDATE
  USING (
    auth.role() = 'service_role' OR
    auth.uid() = storyteller_id
  );

-- room_members policies
DROP POLICY IF EXISTS "room_members_select" ON room_members;
DROP POLICY IF EXISTS "room_members_insert" ON room_members;
DROP POLICY IF EXISTS "room_members_update" ON room_members;
DROP POLICY IF EXISTS "room_members_delete" ON room_members;

CREATE POLICY "room_members_select"
  ON room_members FOR SELECT
  USING (
    auth.role() = 'service_role' OR
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.id = room_members.room_id
        AND gr.storyteller_id = auth.uid()
    )
  );

CREATE POLICY "room_members_insert"
  ON room_members FOR INSERT
  WITH CHECK (
    auth.role() = 'service_role' OR
    (
      auth.uid() = user_id AND (
        (
          role IN ('player', 'observer') AND
          seat_id IS NULL AND
          seen_role_id IS NULL
        ) OR (
          role = 'storyteller' AND
          EXISTS (
            SELECT 1 FROM game_rooms gr
            WHERE gr.id = room_members.room_id
              AND gr.storyteller_id = auth.uid()
          )
        )
      )
    )
  );

CREATE POLICY "room_members_update"
  ON room_members FOR UPDATE
  USING (
    auth.role() = 'service_role' OR
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.id = room_members.room_id
        AND gr.storyteller_id = auth.uid()
    )
  )
  WITH CHECK (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.id = room_members.room_id
        AND gr.storyteller_id = auth.uid()
    ) OR
    (
      auth.uid() = user_id AND
      role IN ('player', 'observer') AND
      EXISTS (
        SELECT 1 FROM room_members rm
        WHERE rm.id = room_members.id
          AND rm.role IS NOT DISTINCT FROM room_members.role
          AND rm.seat_id IS NOT DISTINCT FROM room_members.seat_id
          AND rm.seen_role_id IS NOT DISTINCT FROM room_members.seen_role_id
      )
    )
  );

CREATE POLICY "room_members_delete"
  ON room_members FOR DELETE
  USING (
    auth.role() = 'service_role' OR
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.id = room_members.room_id
        AND gr.storyteller_id = auth.uid()
    )
  );

-- game_secrets policies
DROP POLICY IF EXISTS "game_secrets_select" ON game_secrets;
DROP POLICY IF EXISTS "game_secrets_insert" ON game_secrets;
DROP POLICY IF EXISTS "game_secrets_update" ON game_secrets;
DROP POLICY IF EXISTS "game_secrets_delete" ON game_secrets;

CREATE POLICY "game_secrets_select"
  ON game_secrets FOR SELECT
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.room_code = game_secrets.room_code
        AND gr.storyteller_id = auth.uid()
    )
  );

CREATE POLICY "game_secrets_insert"
  ON game_secrets FOR INSERT
  WITH CHECK (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.room_code = game_secrets.room_code
        AND gr.storyteller_id = auth.uid()
    )
  );

CREATE POLICY "game_secrets_update"
  ON game_secrets FOR UPDATE
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.room_code = game_secrets.room_code
        AND gr.storyteller_id = auth.uid()
    )
  );

CREATE POLICY "game_secrets_delete"
  ON game_secrets FOR DELETE
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.room_code = game_secrets.room_code
        AND gr.storyteller_id = auth.uid()
    )
  );

-- seat_secrets policies (storyteller only)
DROP POLICY IF EXISTS "seat_secrets_select_st_only" ON seat_secrets;
DROP POLICY IF EXISTS "seat_secrets_insert_st_only" ON seat_secrets;
DROP POLICY IF EXISTS "seat_secrets_update_st_only" ON seat_secrets;
DROP POLICY IF EXISTS "seat_secrets_delete_st_only" ON seat_secrets;

CREATE POLICY "seat_secrets_select_st_only"
  ON seat_secrets FOR SELECT
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.id = seat_secrets.room_id
        AND gr.storyteller_id = auth.uid()
    )
  );

CREATE POLICY "seat_secrets_insert_st_only"
  ON seat_secrets FOR INSERT
  WITH CHECK (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.id = seat_secrets.room_id
        AND gr.storyteller_id = auth.uid()
    )
  );

CREATE POLICY "seat_secrets_update_st_only"
  ON seat_secrets FOR UPDATE
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.id = seat_secrets.room_id
        AND gr.storyteller_id = auth.uid()
    )
  );

CREATE POLICY "seat_secrets_delete_st_only"
  ON seat_secrets FOR DELETE
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.id = seat_secrets.room_id
        AND gr.storyteller_id = auth.uid()
    )
  );

-- game_messages policies (members only)
DROP POLICY IF EXISTS "game_messages_select" ON game_messages;
DROP POLICY IF EXISTS "game_messages_insert" ON game_messages;

CREATE POLICY "game_messages_select"
  ON game_messages FOR SELECT
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.id = game_messages.room_id
        AND gr.storyteller_id = auth.uid()
    ) OR
    EXISTS (
      SELECT 1 FROM room_members rm
      WHERE rm.room_id = game_messages.room_id
        AND rm.user_id = auth.uid()
        AND (
          game_messages.recipient_seat_id IS NULL OR
          rm.seat_id = game_messages.sender_seat_id OR
          rm.seat_id = game_messages.recipient_seat_id
        )
    )
  );

CREATE POLICY "game_messages_insert"
  ON game_messages FOR INSERT
  WITH CHECK (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM room_members rm
      WHERE rm.room_id = game_messages.room_id
        AND rm.user_id = auth.uid()
    )
  );

-- interaction_logs policies (storyteller only)
DROP POLICY IF EXISTS "interaction_logs_select" ON interaction_logs;
DROP POLICY IF EXISTS "interaction_logs_insert" ON interaction_logs;
DROP POLICY IF EXISTS "interaction_logs_update" ON interaction_logs;

CREATE POLICY "interaction_logs_select"
  ON interaction_logs FOR SELECT
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM room_members rm
      WHERE rm.room_id = interaction_logs.room_id
        AND rm.user_id = auth.uid()
        AND rm.role = 'storyteller'
    )
  );

CREATE POLICY "interaction_logs_insert"
  ON interaction_logs FOR INSERT
  WITH CHECK (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM room_members rm
      WHERE rm.room_id = interaction_logs.room_id
        AND rm.user_id = auth.uid()
        AND rm.role = 'storyteller'
    )
  );

CREATE POLICY "interaction_logs_update"
  ON interaction_logs FOR UPDATE
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM room_members rm
      WHERE rm.room_id = interaction_logs.room_id
        AND rm.user_id = auth.uid()
        AND rm.role = 'storyteller'
    )
  );

-- daily_nominations policies (storyteller only)
DROP POLICY IF EXISTS "daily_nominations_select" ON daily_nominations;
DROP POLICY IF EXISTS "daily_nominations_insert" ON daily_nominations;
DROP POLICY IF EXISTS "daily_nominations_update" ON daily_nominations;

CREATE POLICY "daily_nominations_select"
  ON daily_nominations FOR SELECT
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM room_members rm
      WHERE rm.room_id = daily_nominations.room_id
        AND rm.user_id = auth.uid()
        AND rm.role = 'storyteller'
    )
  );

CREATE POLICY "daily_nominations_insert"
  ON daily_nominations FOR INSERT
  WITH CHECK (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM room_members rm
      WHERE rm.room_id = daily_nominations.room_id
        AND rm.user_id = auth.uid()
        AND rm.role = 'storyteller'
    )
  );

CREATE POLICY "daily_nominations_update"
  ON daily_nominations FOR UPDATE
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM room_members rm
      WHERE rm.room_id = daily_nominations.room_id
        AND rm.user_id = auth.uid()
        AND rm.role = 'storyteller'
    )
  );

-- game_history policies
DROP POLICY IF EXISTS "game_history_select" ON game_history;
DROP POLICY IF EXISTS "game_history_insert" ON game_history;

CREATE POLICY "game_history_select"
  ON game_history FOR SELECT
  USING (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.room_code = game_history.room_code
        AND gr.storyteller_id = auth.uid()
    ) OR
    EXISTS (
      SELECT 1 FROM room_members rm
      JOIN game_rooms gr ON gr.id = rm.room_id
      WHERE gr.room_code = game_history.room_code
        AND rm.user_id = auth.uid()
    )
  );

CREATE POLICY "game_history_insert"
  ON game_history FOR INSERT
  WITH CHECK (
    auth.role() = 'service_role' OR
    EXISTS (
      SELECT 1 FROM game_rooms gr
      WHERE gr.room_code = game_history.room_code
        AND gr.storyteller_id = auth.uid()
    )
  );
