-- ============================================================
-- v2026-02-08: Push subscriptions + offline operation audit
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  room_code text references game_rooms(room_code) on delete set null,
  endpoint text not null,
  p256dh text not null,
  auth_key text not null,
  user_agent text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, endpoint)
);

create index if not exists idx_push_subscriptions_user_id on push_subscriptions(user_id);
create index if not exists idx_push_subscriptions_room_code on push_subscriptions(room_code);

create table if not exists offline_operation_events (
  id bigint generated by default as identity primary key,
  room_code text not null references game_rooms(room_code) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  operation_id text not null,
  operation_type text not null,
  status text not null check (status in ('success', 'failed', 'deduplicated')),
  error_message text,
  operation_payload jsonb not null default '{}'::jsonb,
  processed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(room_code, user_id, operation_id)
);

create index if not exists idx_offline_operation_events_room_user on offline_operation_events(room_code, user_id);
create index if not exists idx_offline_operation_events_processed_at on offline_operation_events(processed_at desc);

alter table push_subscriptions enable row level security;
alter table offline_operation_events enable row level security;

-- push_subscriptions policies
DROP POLICY IF EXISTS "push_subscriptions_select" ON push_subscriptions;
DROP POLICY IF EXISTS "push_subscriptions_insert" ON push_subscriptions;
DROP POLICY IF EXISTS "push_subscriptions_update" ON push_subscriptions;
DROP POLICY IF EXISTS "push_subscriptions_delete" ON push_subscriptions;

CREATE POLICY "push_subscriptions_select"
  ON push_subscriptions FOR SELECT
  USING (
    auth.role() = 'service_role' OR
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1
      FROM game_rooms gr
      WHERE gr.room_code = push_subscriptions.room_code
        AND gr.storyteller_id = auth.uid()
    )
  );

CREATE POLICY "push_subscriptions_insert"
  ON push_subscriptions FOR INSERT
  WITH CHECK (
    auth.role() = 'service_role' OR
    auth.uid() = user_id
  );

CREATE POLICY "push_subscriptions_update"
  ON push_subscriptions FOR UPDATE
  USING (
    auth.role() = 'service_role' OR
    auth.uid() = user_id
  )
  WITH CHECK (
    auth.role() = 'service_role' OR
    auth.uid() = user_id
  );

CREATE POLICY "push_subscriptions_delete"
  ON push_subscriptions FOR DELETE
  USING (
    auth.role() = 'service_role' OR
    auth.uid() = user_id
  );

-- offline_operation_events policies
DROP POLICY IF EXISTS "offline_operation_events_select" ON offline_operation_events;
DROP POLICY IF EXISTS "offline_operation_events_insert" ON offline_operation_events;
DROP POLICY IF EXISTS "offline_operation_events_update" ON offline_operation_events;
DROP POLICY IF EXISTS "offline_operation_events_delete" ON offline_operation_events;

CREATE POLICY "offline_operation_events_select"
  ON offline_operation_events FOR SELECT
  USING (
    auth.role() = 'service_role' OR
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1
      FROM game_rooms gr
      WHERE gr.room_code = offline_operation_events.room_code
        AND gr.storyteller_id = auth.uid()
    )
  );

CREATE POLICY "offline_operation_events_insert"
  ON offline_operation_events FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "offline_operation_events_update"
  ON offline_operation_events FOR UPDATE
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "offline_operation_events_delete"
  ON offline_operation_events FOR DELETE
  USING (auth.role() = 'service_role');
