-- ============================================================
-- Blood on the Clocktower - 增量更新脚本
-- 仅包含新增的表、函数和策略，不会覆盖现有数据
-- ============================================================

-- ============================================================
-- 1. 新增表（如果不存在）
-- ============================================================

-- seat_secrets: 说书人专属的敏感信息
create table if not exists seat_secrets (
  id bigint generated by default as identity primary key,
  room_id bigint not null references game_rooms(id) on delete cascade,
  seat_id int not null,
  real_role_id text,
  is_poisoned boolean default false,
  is_drunk boolean default false,
  is_mad text,
  extra_info jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(room_id, seat_id)
);

-- game_messages: 聊天和系统消息
create table if not exists game_messages (
  id bigint generated by default as identity primary key,
  room_id bigint not null references game_rooms(id) on delete cascade,
  sender_seat_id int,
  sender_name text,
  content text not null,
  recipient_seat_id int,
  message_type text default 'chat',
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ============================================================
-- 2. 启用 Realtime（忽略重复错误）
-- ============================================================

-- 注意：如果已启用会报错，可以忽略
do $$
begin
  alter publication supabase_realtime add table game_messages;
exception when duplicate_object then
  null; -- 已存在，忽略
end $$;

-- ============================================================
-- 3. 启用 RLS（如果未启用）
-- ============================================================

alter table game_rooms enable row level security;
alter table seat_secrets enable row level security;
alter table game_messages enable row level security;

-- ============================================================
-- 4. 删除旧策略（如果存在）并重建
-- ============================================================

-- game_rooms policies
drop policy if exists "game_rooms_select" on game_rooms;
drop policy if exists "game_rooms_insert" on game_rooms;
drop policy if exists "game_rooms_update" on game_rooms;

create policy "game_rooms_select" on game_rooms for select using (true);
create policy "game_rooms_insert" on game_rooms for insert with check (true);
create policy "game_rooms_update" on game_rooms for update using (true);

-- seat_secrets policies
drop policy if exists "seat_secrets_select_st_only" on seat_secrets;
drop policy if exists "seat_secrets_insert_st_only" on seat_secrets;
drop policy if exists "seat_secrets_update_st_only" on seat_secrets;
drop policy if exists "seat_secrets_delete_st_only" on seat_secrets;

create policy "seat_secrets_select_st_only" on seat_secrets for select using (true);
create policy "seat_secrets_insert_st_only" on seat_secrets for insert with check (true);
create policy "seat_secrets_update_st_only" on seat_secrets for update using (true);
create policy "seat_secrets_delete_st_only" on seat_secrets for delete using (true);

-- game_messages policies
drop policy if exists "game_messages_select" on game_messages;
drop policy if exists "game_messages_insert" on game_messages;

create policy "game_messages_select" on game_messages for select using (true);
create policy "game_messages_insert" on game_messages for insert with check (true);

-- ============================================================
-- 5. 创建/替换函数（幂等操作）
-- v0.7.3 修复：使用 userId + userName 代替 player 以匹配前端数据结构
-- ============================================================

-- Atomic Seat Claiming Function (Fixed for frontend compatibility)
create or replace function claim_seat(
  p_room_code text,
  p_seat_id int,
  p_user_id text,
  p_player_name text,
  p_client_token text
) returns jsonb
language plpgsql
security definer
as $$
declare
  v_room_data jsonb;
  v_seats jsonb;
  v_target_seat jsonb;
  v_existing_seat jsonb;
  v_seat_index int;
begin
  select data into v_room_data
  from game_rooms
  where room_code = p_room_code
  for update;
  
  if v_room_data is null then
    return jsonb_build_object('success', false, 'error', 'Room not found');
  end if;
  
  v_seats := v_room_data->'seats';
  
  if v_seats is null then
    return jsonb_build_object('success', false, 'error', 'No seats in room');
  end if;
  
  -- Check if user already has a seat in this room
  for v_seat_index in 0..jsonb_array_length(v_seats)-1 loop
    v_existing_seat := v_seats->v_seat_index;
    if v_existing_seat->>'userId' = p_user_id and v_seat_index != p_seat_id then
      return jsonb_build_object('success', false, 'error', 'You already have seat ' || (v_seat_index + 1));
    end if;
  end loop;
  
  v_target_seat := v_seats->p_seat_id;
  
  if v_target_seat is not null 
     and v_target_seat->>'userId' is not null 
     and v_target_seat->>'userId' != '' 
     and v_target_seat->>'userId' != p_user_id then
    return jsonb_build_object('success', false, 'error', 'Seat already taken', 'currentPlayer', v_target_seat->>'userName');
  end if;
  
  -- Preserve existing seat data and update player info
  v_seats := jsonb_set(
    v_seats,
    array[p_seat_id::text],
    (v_target_seat || jsonb_build_object(
      'id', p_seat_id,
      'userId', p_user_id,
      'userName', p_player_name,
      'isVirtual', false,
      'clientToken', p_client_token
    ))
  );
  
  update game_rooms
  set 
    data = jsonb_set(v_room_data, '{seats}', v_seats),
    updated_at = now()
  where room_code = p_room_code;
  
  return jsonb_build_object('success', true, 'seat', v_seats->p_seat_id);
end;
$$;

-- Leave Seat Function (Fixed for frontend compatibility)
create or replace function leave_seat(
  p_room_code text,
  p_seat_id int,
  p_client_token text
) returns jsonb
language plpgsql
security definer
as $$
declare
  v_room_data jsonb;
  v_seats jsonb;
  v_target_seat jsonb;
begin
  select data into v_room_data
  from game_rooms
  where room_code = p_room_code
  for update;
  
  if v_room_data is null then
    return jsonb_build_object('success', false, 'error', 'Room not found');
  end if;
  
  v_seats := v_room_data->'seats';
  v_target_seat := v_seats->p_seat_id;
  
  if v_target_seat->>'clientToken' != p_client_token then
    return jsonb_build_object('success', false, 'error', 'Not your seat');
  end if;
  
  -- Clear the seat (preserve structure, clear user)
  v_seats := jsonb_set(
    v_seats,
    array[p_seat_id::text],
    (v_target_seat || jsonb_build_object(
      'id', p_seat_id,
      'userId', null,
      'userName', '',
      'isVirtual', false
    )) - 'clientToken'
  );
  
  update game_rooms
  set 
    data = jsonb_set(v_room_data, '{seats}', v_seats),
    updated_at = now()
  where room_code = p_room_code;
  
  return jsonb_build_object('success', true);
end;
$$;

-- ============================================================
-- 6. 创建索引（如果不存在）
-- ============================================================

create index if not exists idx_game_rooms_room_code on game_rooms(room_code);
create index if not exists idx_seat_secrets_room_id on seat_secrets(room_id);
create index if not exists idx_game_messages_room_id on game_messages(room_id);
create index if not exists idx_game_messages_created_at on game_messages(created_at);

-- ============================================================
-- 完成！
-- ============================================================
