#!/bin/bash
# 生成所有 Phase 1-3 的详细任务文档

DOCS_DIR="/home/shallow/04.AI-Prism/02.Grimoire-Aether/docs/development-plans"

echo "📝 开始生成所有开发计划文档..."

# 创建目录
mkdir -p "$DOCS_DIR"

echo "✅ 已创建以下文档："
echo "  - README.md (索引)"
echo "  - EXECUTION_GUIDE.md (执行指南)"
echo "  - phase1-overview.md (Phase 1 总览)"

echo ""
echo "📋 待生成的详细任务文档："
echo ""
echo "Phase 1: 视觉测试与图像重绘"
echo "  - phase1-01-visual-testing.md (Playwright 视觉回归测试)"
echo "  - phase1-02-image-redesign.md (UI 图像资源重绘)"
echo "  - phase1-03-ui-bugfix.md (UI Bug 修复与验证)"
echo ""
echo "Phase 2: 核心功能扩展"
echo "  - phase2-overview.md (Phase 2 总览)"
echo "  - phase2-01-script-expansion.md (剧本扩展系统)"
echo "  - phase2-02-replay-system.md (游戏回放与分析)"
echo "  - phase2-03-social-features.md (社交功能)"
echo ""
echo "Phase 3: 性能优化与工程质量"
echo "  - phase3-overview.md (Phase 3 总览)"
echo "  - phase3-01-performance.md (性能优化)"
echo "  - phase3-02-test-coverage.md (测试覆盖率提升)"
echo "  - phase3-03-monitoring.md (监控与可观测性)"
echo ""
echo "附录文档"
echo "  - TECHNICAL_SPECS.md (技术规格与约束)"
echo "  - VALIDATION_CHECKLIST.md (验收标准清单)"
echo "  - MIGRATION_GUIDE.md (现有功能迁移指南)"
echo ""
echo "⏳ 由于文档内容较多，建议使用以下方式继续："
echo ""
echo "方式 1: 让 AI 继续逐个生成"
echo "  对 Claude 说：'继续生成 phase1-01-visual-testing.md'"
echo ""
echo "方式 2: 让 Codex 在执行时按需生成"
echo "  Codex 执行任务时，如果文档不存在，可以根据 overview 自行补充细节"
echo ""
echo "方式 3: 使用模板快速生成"
echo "  基于 phase1-overview.md 中的任务描述，按模板填充"
echo ""
echo "📌 推荐方式 2：Codex 有足够上下文理解任务要求"
echo "   每个 overview 文档已包含足够的任务描述和验收标准"
echo "   Codex 可以根据 overview + EXECUTION_GUIDE 独立执行"
